### ISSUE TITLE
Monstrorvm isn't working well with multiple dimensions. [BUG]

### ISSUE THREAD

**Issue by TheGam1ngWizard** [Steel-Dev/Monstrorvm#2]
Monstrovm doesn't spawn mobs in dimensions that are 'nether' type built through multiverse. 
Our server has both betternetherite and monstrorvm, and mobs aren't spawning in our 'SurvivalWorld_nether' world.

A potential fix would be adding a config option to specify what dimensions monstrorvm should spawn in.

Thank you for your time!
-Wizard

**Comment by Steel-Dev** [comment]
Hey! Thanks for this report - May I know what version of Monstrorvm you are running?
In 1.0.7 I changed the valid spawn worlds node for custom mobs so you can specify world names instead of environments, so you can better control spawns. If you are on 1.0.7 or above and this change isn't functioning properly, this is indeed a bug. If you're outdated you can view the most recent version here: https://www.spigotmc.org/resources/monstrorvm.85464/updates

**Comment by TheGam1ngWizard** [comment]
My monstrorvm version states 1.0.8. And I don't see that option in my config. I can try some troubleshooting (like reloading the config) if that's out of date.
`# Enable debug messages?
#  WARNING: WILL cause spam in console! this is
#   a development option, put here for ease of development.
Debug: true
ExamplesEnabled: true
UpdateCheck:
  MessageOnJoin: true
  MessageOnReload: true
CustomMobs:
  MobCap: 100
Prefix: '&2Monstrorvm &7Â» '
Reload:
  ShowErrors: true
  ShowWarnings: true
`

**Comment by Steel-Dev** [comment]
It'll be in the yml file for your custom mob.
For instance; in the 'Valid Spawn Environments' instead of putting 'NORMAL' or 'NETHER' or 'THE_END', you can just put the name of the world, like so:
```
ValidSpawnEnvironments:
  - world
  - SurvivalWorld_nether
```
You can list as many as you wish!

The config should auto-update if any changes are made to it, so that shouldn't be a problem.

**Comment by TheGam1ngWizard** [comment]
Ahh, I think I might have miscommunicated what my issue was. I'm not actually using monstrorvm for any of my own custom mobs. my primary issue is that I'm not seeing the BetterNetherite custom mobs (that got moved into monstrorvm a while back).

**Comment by Steel-Dev** [comment]
Ohhh, okay that's an issue on Better Netherites end
My bad, I misunderstood!
Okay, I'll add extra config options for the Better Netherite mobs in Better Netherite so you can define worlds for them to spawn in.
I'll let you know when that update is out!

**Comment by TheGam1ngWizard** [comment]
Thanks for your time and sorry for the confusion!

**Comment by Steel-Dev** [comment]
You're very welcome, and it's okay! I really appreciate this report, I'll get to fixing it for you right away!

**Comment by Steel-Dev** [comment]
Hey! I've made the change, done some testing - but I'd like to let you have a build here to test and see if everything is all good before I publish this update. 

Please note; do not set the spawn chance to be insanely high as the mobs will spawn non-stop and overload the server, this IS a bug with Monstrorvm I will be fixing with the next (massive btw) update. (though, it is quite entertaining to watch - but I don't recommend it)

Download it [here](https://drive.google.com/file/d/17BCa1CaeJqrU0gJ5JraH5WmbmZQ4gbLq/view?usp=sharing) (I can't upload it directly via github, I'm so sorry). 

Do please let me know if it works and if any issues arise!

**Comment by TheGam1ngWizard** [comment]
I setup the dev build, and it worked! I saw the custom mobs spawning in the world after I got the config all setup.

I'm unsure of any issues that might pop up, but I'll keep an eye out. 
With that though, I'll close out this issue- the new build resolves my issue!

**Comment by Steel-Dev** [comment]
Perfect! Publishing an official release now. Thank you for the report and trying it out!
